DARK_NET_PATH = "../darknet/"
DARK_NET_CFG_PATH = DARK_NET_PATH + "cfg/"
DARK_NET_PYTHON_MODULE_PATH = DARK_NET_PATH
WEIGHT_PATH = DARK_NET_PATH+"/weights/"

EXTRACTOR_PYTHON_MODULE_PATH = "../camera.0511.vn-GetStreamLinkPython/"

VIDEO_EXTRACT_OUTPUT_PATH = "../../Desktop/Trash/"
IMAGE_DETECT_INPUT_PATH = VIDEO_EXTRACT_OUTPUT_PATH
