DARK_NET_PATH = "lib/darknet/"
DARK_NET_CFG_PATH = DARK_NET_PATH + "cfg/"
DARK_NET_PYTHON_MODULE_PATH = DARK_NET_PATH


VIDEO_EXTRACT_OUTPUT_PATH = "./out/"
IMAGE_DETECT_INPUT_PATH = VIDEO_EXTRACT_OUTPUT_PATH
DARKNET_IMAGE_DETECT_INPUT_PATH = "/Users/phantruongthanh/Git/darknet/data/"
IMAGE_DETECT_OUTPUT_PATH = VIDEO_EXTRACT_OUTPUT_PATH + "out/"
